export const categories = [
  { value: "INTERNSHIP", label: "Internships", icon: "💼" },
  { value: "CERTIFICATION", label: "Certifications", icon: "📜" },
  { value: "HACKATHON", label: "Hackathons", icon: "🏆" },
  { value: "COMPETITION", label: "Competitions", icon: "🎯" },
  { value: "RESEARCH", label: "Research", icon: "🔬" },
  { value: "OPEN_SOURCE", label: "Open Source", icon: "🌐" },
  { value: "SCHOLARSHIP", label: "Scholarships", icon: "🎓" },
  { value: "COURSE", label: "Courses", icon: "📚" },
  { value: "WORKSHOP", label: "Workshops", icon: "🛠️" },
] as const;

export const difficulties = [
  { value: "BEGINNER", label: "Beginner" },
  { value: "EASY", label: "Easy" },
  { value: "MEDIUM", label: "Medium" },
  { value: "HARD", label: "Hard" },
  { value: "EXPERT", label: "Expert" },
] as const;

export const skills = [
  "Python",
  "JavaScript",
  "TypeScript",
  "Java",
  "C++",
  "Go",
  "Rust",
  "React",
  "Next.js",
  "Node.js",
  "Django",
  "Flask",
  "Spring Boot",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "Data Science",
  "Cloud Computing",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "DevOps",
  "Cybersecurity",
  "Blockchain",
  "Web Development",
  "Mobile Development",
  "UI/UX Design",
  "Database Design",
  "SQL",
  "NoSQL",
  "Git",
  "Linux",
  "REST APIs",
  "GraphQL",
  "Microservices",
  "Agile",
  "System Design",
] as const;

export const notificationTypes = [
  { value: "NEW_OPPORTUNITY", label: "New Opportunities" },
  { value: "DEADLINE_REMINDER", label: "Deadline Reminders" },
  { value: "APPLICATION_REMINDER", label: "Application Reminders" },
  { value: "CERTIFICATION_EXPIRING", label: "Certification Expiring" },
  { value: "WEEKLY_DIGEST", label: "Weekly Digest" },
] as const;

export const locations = [
  "Remote",
  "Bangalore, India",
  "Hyderabad, India",
  "Pune, India",
  "Delhi NCR, India",
  "Mumbai, India",
  "Chennai, India",
  "San Francisco, USA",
  "New York, USA",
  "Seattle, USA",
  "London, UK",
  "Berlin, Germany",
  "Toronto, Canada",
  "Global",
  "Online",
] as const;
